server:
  port: 8124

spring:
  security:
    enabled: false
    
kafka:
  topic:
    config-update: config-server-update-1

event-type-list: >
  {"MobileOTPVerification":{"name":"MobileOTPVerification","enabled":true,"notifyCustomer":true,"notificationChannel":[{"smsNotificationService":{"templateId":"1234","enabled":true}},{"emailNotificationService":{"templateId":"4321","enabled":true}}],"archivalTTL":5},"EmailOTPVerification":{"name":"EmailOTPVerification","enabled":true,"notifyCustomer":true,"notificationChannel":[{"smsNotificationService":{"templateId":"1234","enabled":true}},{"emailNotificationService":{"templateId":"4321","enabled":true}}],"archivalTTL":5},"kfsEvent":{"name":"kfsEvent","enabled":true,"notifyCustomer":false,"notificationChannel":[{"smsNotificationService":{"templateId":"1234","enabled":false}},{"emailNotificationService":{"templateId":"4321","enabled":false}}],"archivalTTL":5}}
country-code-list: >
  {"countryList":[{"code":"IN","countryName":"India","countryCode":"+91","imageUrl":"/external/images/india-flag.svg","validation":{"minLength":10,"maxLength":10,"pattern":"^[6-9]\\d{9}$","stripPattern":"[\\s-]"},"errorMessages":{"required":"Mobile number is required","invalid":"Please enter a valid mobile number","invalidLength":"Mobile number must be 10 digits"}},{"code":"PL","countryName":"Poland","countryCode":"+48","imageUrl":"/external/images/poland-flag.svg","validation":{"minLength":9,"maxLength":9,"pattern":"^\\d{9}$","stripPattern":"[\\s-]"},"errorMessages":{"required":"Mobile number is required","invalid":"Please enter a valid mobile number","invalidLength":"Mobile number must be 9 digits"}}]}
